project: "LB-SAC"
group: "lb-sac-halfcheetah-full-replay-v2-multiseed-v0"
name: "sac"
dataset_name: "halfcheetah-full-replay-v2"
num_critics: 4
batch_size: 10000
actor_lr: 0.0018
critic_lr: 0.0018
alpha_lr: 0.0018
num_epochs: 350