project: "LB-SAC"
group: "sac-halfcheetah-edac-init-batch-scaling"
name: "sac-n-256"
num_critics: 5
batch_size: 256
num_epochs: 400
critic_use_layernorm: true
dataset_name: "halfcheetah-medium-v2"
edac_init: true
edac_style_critic_loss: true