project: "LB-SAC"
group: "sac-halfcheetah-edac-init-batch-scaling"
name: "sac-n-20k"
num_critics: 5
batch_size: 20000
actor_lr: 0.0026
critic_lr: 0.0026
alpha_lr: 0.0026
num_epochs: 400
critic_use_layernorm: true
dataset_name: "halfcheetah-medium-v2"
edac_init: true
edac_style_critic_loss: true