project: "LB-SAC"
group: "sac-halfcheetah-edac-init-batch-scaling"
name: "sac-n-40k"
num_critics: 5
batch_size: 40000
actor_lr: 0.0037
critic_lr: 0.0037
alpha_lr: 0.0037
num_epochs: 400
critic_use_layernorm: true
dataset_name: "halfcheetah-medium-v2"
edac_init: true
edac_style_critic_loss: true