project: "LB-SAC"
group: "sac-n-hopper-medium-replay-v2-multiseed-v0"
name: "sac-n"
num_critics: 200
num_epochs: 3000
dataset_name: "hopper-medium-replay-v2"
edac_init: true
edac_style_critic_loss: true