project: "LB-SAC"
group: "lb-sac-walker2d-expert-v2-multiseed-v0"
name: "lb-sac"
dataset_name: "walker2d-expert-v2"
num_critics: 30
batch_size: 10000
actor_lr: 0.0018
critic_lr: 0.0018
alpha_lr: 0.0018
num_epochs: 350
edac_init: true
